server:
  port: 8082
spring:
  webflux:
    base-path: /api/user
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
  kafka:
    bootstrap-servers: localhost:9092
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    web: debug
    org:
      springframework:
        data.mongodb: debug
jwt:
  secretKey: dsaijodajadsjdsalkjadslkjadsljlajkdslkjadslkjadsjlklsad
  accessTokenExpire: 30
  refreshTokenExpire: 60
url:
  frontend: http://localhost:3000
  service:
    auth: http://localhost:8081
    user: http://localhost:8082
    quiz: http://localhost:8083