spring:
  data:
    mongodb:
      uri: ${USER_DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
jwt:
  secretKey: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
url:
  frontend: https://quizit.org
  service:
    auth: auth-service/api/auth
    user: user-service/api/user
    quiz: quiz-service/api/quiz