spring:
  data:
    mongodb:
      uri: ${USER_DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
jwt:
  secretKey: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
logging:
  level:
    web: debug
    org:
      springframework:
        data.mongodb: debug
url:
  frontend: ${FRONTEND_URL}
  service:
    auth: auth-service
    user: user-service
    quiz: quiz-service