server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
  kafka:
    bootstrap-servers: localhost:9092
jwt:
  secretKey: dsaijodajadsjdsalkjadslkjadsljlajkdslkjadslkjadsjlklsad
  accessTokenExpire: 30
  refreshTokenExpire: 60
url:
  frontend: http://localhost:3000
  service:
    auth: http://localhost:8081/api/auth
    user: http://localhost:8082/api/user
    quiz: http://localhost:8083/api/quiz
logging:
  level:
    org.springframework:
      data.mongodb: debug