spring:
  webflux:
    base-path: /api/user
  data:
    mongodb:
      uri: ${USER_DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
jwt:
  secretKey: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
url:
  frontend: ${FRONTEND_URL}
  service:
    auth: auth-service
    user: user-service
    quiz: quiz-service